default_language_version:
    python: python3.9

default_stages: [commit, push]

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.4.0
      hooks:
          - id: check-yaml
            name: Check YAML files

          - id: check-toml
            name: Check Toml files

          - id: check-json
            name: Check JSON files

          - id: check-case-conflict
            name: Check file name case conflicts

          - id: check-merge-conflict
            name: Check merge conflicts not resolved

          - id: check-symlinks
            name: Check missing targets for symlinks

          - id: destroyed-symlinks
            name: Check for symlinks converted to file

          - id: end-of-file-fixer
            name: Fix End of Files

          - id: trailing-whitespace
            name: Trim Trailing Whitespace

          - id: check-added-large-files
            name: Check for added large files

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.1.2
      hooks:
          - id: prettier
            name: Prettifying non-Python files
            exclude_types: [python]

    - repo: https://github.com/jorisroovers/gitlint
      rev: v0.15.0
      hooks:
          - id: gitlint
            name: Validating Git commit message
            stages: [commit-msg]

    - repo: local
      hooks:
          - id: black
            name: Format code
            entry: /usr/bin/env sh -c 'poetry run task style-black "$@" && git add -u' --
            language: system
            types: [python]
            stages: [prepare-commit-msg]
            require_serial: true

          - id: isort
            name: Reorder imports
            entry: /usr/bin/env sh -c 'poetry run task style-isort "$@" && git add -u' --
            language: system
            types: [python]
            stages: [prepare-commit-msg]
            require_serial: true

          - id: my-py
            name: Static type checker
            entry: poetry run task lint-mypy
            language: system
            files: ^src/.*\.py$

          - id: flake8
            name: Static analysis
            entry: poetry run task lint-flake
            language: system
            files: ^src/.*\.py$

          - id: safety
            name: Checking security
            entry: poetry run task lint-safety
            language: system
            files: ^src/.*\.py$

          - id: wily-build
            name: Updating complexity cache
            entry: poetry run task complexity-build
            language: python
            stages: [post-commit]
            additional_dependencies: [wily]
            require_serial: true

          - id: wily
            name: Complexity analysis
            entry: poetry run task complexity-wily diff
            language: python
            additional_dependencies: [wily]
            require_serial: true
