default_language_version:
    python: python3.9

default_stages: [commit, push]

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.5.0
      hooks:
          - id: check-yaml
            name: Check YAML files
            types: [yaml]

          - id: check-toml
            name: Check Toml files
            types: [toml]

          - id: check-json
            name: Check JSON files
            types: [json]

          - id: end-of-file-fixer
            name: Fix End of Files
            types: [text]
            stages: [commit, push, manual]

          - id: trailing-whitespace
            name: Trim Trailing Whitespace
            types: [text]
            stages: [commit, push, manual]

          - id: check-added-large-files
            name: Check for added large files

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.1.2
      hooks:
          - id: prettier
            name: Prettifying non-Python files
            exclude_types: [python]

    - repo: local
      hooks:
          - id: black
            name: Format code
            entry: /usr/bin/env sh -c 'poetry run task style-black "$@" && git add -u' --
            language: system
            types: [python]
            stages: [prepare-commit-msg]
            require_serial: true

          - id: isort
            name: Reorder imports
            entry: /usr/bin/env sh -c 'poetry run task style-isort "$@" && git add -u' --
            language: system
            types: [python]
            stages: [prepare-commit-msg]
            require_serial: true

          - id: my-py
            name: Checking type-hints
            entry: poetry run task lint-mypy
            language: system
            files: ^src/.*\.py$

          - id: flake8
            name: Static analysis
            entry: poetry run task lint-flake
            language: system
            files: ^src/.*\.py$

          - id: safety
            name: Checking security
            entry: poetry run task lint-safety
            language: system
            files: pyproject\.toml

          - id: wily
            name: wily
            entry: poetry run wily diff
            verbose: true
            language: python
            additional_dependencies: [wily]
