default_language_version:
  python: python3.7

default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
        name: Check YAML files
        types: [yaml]

      - id: check-toml
        name: Check Toml files
        types: [toml]

      - id: check-json
        name: Check JSON files
        types: [json]

      - id: end-of-file-fixer
        name: Fix End of Files
        types: [text]
        stages: [commit, push, manual]

      - id: trailing-whitespace
        name: Trim Trailing Whitespace
        types: [text]
        stages: [commit, push, manual]

      - id: check-added-large-files
        name: Check for added large files


  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.1.2
    hooks:
      - id: prettier
        name: Prettifying non-Python files
        exclude_types: [python]

  - repo: local
    hooks:
      - id: isort
        name: Sort imports (isort)
        entry: poetry run isort --settings-path pyproject.toml
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: black
        name: Code formatting (black)
        entry: poetry run black --config pyproject.toml
        language: system
        types: [python]
        require_serial: true

  - repo: local
    hooks:
      - id: flake8
        name: Static analysis (flake8)
        entry: flake8
        language: system
        types: [python]
